### PR TITLE
Added support for non-integer versions

### PR DESCRIPTION
**Pull request by alexschimpf**

### CODE REVIEW

**Comment by ndejong** [comment]
There is a test in `test_advanced.py` that fails for me
- python 3.10.6
- new venv with `python -m venv .venv`
- activate the venv
- install the development requirements `pip install -r requirements.dev.txt`

Pytest -
```
(.venv) ndejong@computerd ~/fastapi-versionizer-alexschimpf (alex/non-integer-versions)$ pytest
==================================================================================== test session starts =====================================================================================
platform linux -- Python 3.10.6, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/ndejong/cyberco/projects/fastapi-versionizer-alexschimpf
plugins: anyio-3.6.2
collected 5 items

tests/test_advanced.py F                                                                                                                                                               [ 20%]
tests/test_non_integer_versions.py .                                                                                                                                                   [ 40%]
tests/test_simple.py .                                                                                                                                                                 [ 60%]
tests/test_sorted.py .                                                                                                                                                                 [ 80%]
tests/test_versioned_api_route.py .                                                                                                                                                    [100%]

========================================================================================== FAILURES ==========================================================================================
_________________________________________________________________________________ TestAdvanced.test_advanced _________________________________________________________________________________

self = <tests.test_advanced.TestAdvanced testMethod=test_advanced>

>   ???
E   AssertionError: {'/do[1042 chars]a': {}}}}, '400': {'description': 'Bad Request[248 chars]}}}}} != {'/do[1042 chars]a': {'title': 'Response Do Something Else Do S[308 chars]}}}}}
E     {'/do_something': {'post': {'description': 'default version -> /do_something',
E                                 'operationId': 'do_something_do_something_post',
E                                 'requestBody': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/TestModel'}}},
E                                                 'required': True},
E                                 'responses': {'200': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/TestModel'}}},
E                                                       'description': 'Successful '
E                                                                      'Response'},
E                                               '400': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ErrorResponsesModel'}}},
E                                                       'description': 'Bad Request'},
E                                               '500': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ErrorResponsesModel'}}},
E                                                       'description': 'Internal '
E                                                                      'Server '
E                                                                      'Error'}},
E                                 'summary': 'Do Something',
E                                 'tags': ['Something']}},
E      '/do_something_else': {'post': {'description': 'default version -> '
E                                                     '/do_something_else',
E                                      'operationId': 'do_something_else_do_something_else_post',
E   -                                  'responses': {'200': {'content': {'application/json': {'schema': {}}},
E   ?                                                                                                    ^^^^
E
E   +                                  'responses': {'200': {'content': {'application/json': {'schema': {'title': 'Response '
E   ?                                                                                                    ^^^^^^^^^^^^^^^^^^^^
E
E   +                                                                                                             'Do '
E   +                                                                                                             'Something '
E   +                                                                                                             'Else '
E   +                                                                                                             'Do '
E   +                                                                                                             'Something '
E   +                                                                                                             'Else '
E   +                                                                                                             'Post'}}},
E                                                            'description': 'Successful '
E                                                                           'Response'},
E                                                    '400': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ErrorResponsesModel'}}},
E                                                            'description': 'Bad '
E                                                                           'Request'},
E                                                    '500': {'content': {'application/json': {'schema': {'$ref': '#/components/schemas/ErrorResponsesModel'}}},
E                                                            'description': 'Internal '
E                                                                           'Server '
E                                                                           'Error'}},
E                                      'summary': 'Do Something Else',
E                                      'tags': ['Something Else']}}}

/home/ndejong/cyberco/projects/fast/fastapi-versionizer/tests/test_advanced.py:122: AssertionError
================================================================================== short test summary info ===================================================================================
FAILED tests/test_advanced.py::TestAdvanced::test_advanced - AssertionError: {'/do[1042 chars]a': {}}}}, '400': {'description': 'Bad Request[248 chars]}}}}} != {'/do[1042 chars]a': {'titl...
================================================================================ 1 failed, 4 passed in 9.68s =================================================================================

```

Pip freeze -
```
anyio==3.6.2
asgiref==3.6.0
attrs==23.1.0
bleach==6.0.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==3.1.0
click==8.1.3
colorama==0.4.6
cryptography==40.0.2
docutils==0.19
fastapi==0.95.1
h11==0.12.0
httpcore==0.14.7
httpx==0.22.0
idna==3.4
importlib-metadata==6.6.0
iniconfig==2.0.0
jaraco.classes==3.2.3
jeepney==0.8.0
keyring==23.13.1
more-itertools==9.1.0
mypy==0.971
mypy-extensions==1.0.0
packaging==23.1
pkginfo==1.9.6
pluggy==1.0.0
py==1.11.0
pycparser==2.21
pydantic==1.9.2
Pygments==2.15.1
pytest==7.0.1
readme-renderer==37.3
requests==2.28.2
requests-toolbelt==0.10.1
rfc3986==1.5.0
SecretStorage==3.3.3
six==1.16.0
sniffio==1.3.0
starlette==0.26.1
tomli==2.0.1
tqdm==4.65.0
twine==3.8.0
types-setuptools==65.6.0.2
typing_extensions==4.5.0
urllib3==1.26.15
uvicorn==0.16.0
webencodings==0.5.1
zipp==3.15.0
```

**Comment by kunesj** [comment]
All tests work for me, so it might be a problem with a specific Python or fastapi version.
```
$ make run-tests 
pytest tests/*
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.11.1, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/kunesj/PycharmProjects/fastapi-versionizer
plugins: anyio-3.6.2
collected 6 items                                                                                                                                                                                                 

tests/test_advanced.py ..                                                                                                                                                                                   [ 16%]
tests/test_non_integer_versions.py .                                                                                                                                                                        [ 33%]
tests/test_simple.py .                                                                                                                                                                                      [ 50%]
tests/test_sorted.py .                                                                                                                                                                                      [ 66%]
tests/test_versioned_api_route.py .

================================================================================================ 6 passed in 0.98s ================================================================================================
```
```
$ pip freeze
aioconsole==0.5.1
aiofiles==22.1.0
aiohttp==3.8.3
aiosignal==1.3.1
aiosmtplib==2.0.0
anyio==3.6.2
appdirs==1.4.4
APScheduler==3.10.1
asgiref==3.6.0
async-timeout==4.0.2
attrs==22.2.0
black==22.10.0
bleach==6.0.0
blessed==1.19.1
boto3==1.26.25
boto3-stubs==1.26.25
botocore==1.29.25
botocore-stubs==1.29.25
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
cryptography==38.0.3
dnspython==2.2.1
docutils==0.19
ecdsa==0.18.0
email-validator==1.3.0
emoji==2.2.0
enlighten==1.11.1
fastapi==0.87.0
fastapi-versionizer==0.1.5
fastapi_amis_admin==0.4.2
frozenlist==1.3.3
greenlet==2.0.1
h11==0.14.0
html2text==2020.1.16
httpcore==0.16.3
httptools==0.5.0
httpx==0.23.3
idna==3.4
IMAPClient==2.3.1
importlib-metadata==6.1.0
iniconfig==2.0.0
isort==5.12.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jeepney==0.8.0
Jinja2==3.1.2
jmespath==1.0.1
keyring==23.13.1
limits==1.6
lxml==4.9.2
Mako==1.2.4
Markdown==3.4.1
MarkupSafe==2.1.1
more-itertools==9.1.0
motor==3.1.1
motor-types==1.0.0b1
multidict==6.0.3
mypy==0.971
mypy-boto3-cloudformation==1.26.60
mypy-boto3-dynamodb==1.26.97.post1
mypy-boto3-ec2==1.26.97.post1
mypy-boto3-lambda==1.26.80
mypy-boto3-rds==1.26.99
mypy-boto3-s3==1.26.99
mypy-boto3-sqs==1.26.0.post1
mypy-extensions==1.0.0
ntlm-auth==1.5.0
orjson==3.8.2
packaging==21.3
pathspec==0.11.1
pdoc3==0.10.0
pkginfo==1.9.6
platformdirs==3.2.0
pluggy==1.0.0
prefixed==0.5.0
psycopg==3.1.4
psycopg-c==3.1.4
psycopg-pool==3.1.4
psycopg2==2.9.5
py==1.11.0
pyasn1==0.4.8
pycparser==2.21
pydantic==1.10.2
Pygments==2.14.0
pyjson5==1.6.2
pymongo==4.3.3
pyOpenSSL==23.0.0
pyparsing==3.0.9
pytest==7.0.1
python-dateutil==2.8.2
python-dotenv==0.21.0
python-jose==3.3.0
python-magic==0.4.27
python-multipart==0.0.5
pytz==2022.6
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
readme-renderer==37.3
requests==2.28.1
requests-ntlm==1.1.0
requests-toolbelt==0.10.1
rfc3986==1.5.0
rsa==4.9
s3transfer==0.6.0
schedule==1.1.0
SecretStorage==3.3.3
six==1.16.0
slowapi==0.1.6
sniffio==1.3.0
SQLAlchemy==1.4.41
sqlalchemy2-stubs==0.0.2a29
sqlalchemy_database==0.1.0
sqlmodel==0.0.8
starlette==0.21.0
tomli==2.0.1
tqdm==4.65.0
twine==3.8.0
types-appdirs==1.4.3.5
types-awscrt==0.16.1
types-beautifulsoup4==4.12.0.1
types-html5lib==1.1.11.13
types-lxml==2023.3.28
types-pyasn1==0.4.0.5
types-pyOpenSSL==23.1.0.1
types-python-dateutil==2.8.19.11
types-python-jose==3.3.4.6
types-pytz==2023.2.0.1
types-requests==2.28.11.16
types-s3transfer==0.6.0.post5
types-setuptools==65.6.0.2
types-urllib3==1.26.25.9
typing_extensions==4.4.0
tzdata==2022.7
tzlocal==4.2
ujson==5.5.0
urllib3==1.26.12
uvicorn==0.20.0
uvloop==0.17.0
watchfiles==0.18.1
wcwidth==0.2.5
webencodings==0.5.1
websockets==10.4
yarl==1.8.2
zipp==3.15.0
```

**Comment by kunesj** [comment]
Also, I think it would be good if type of `version_format` and `prefix_format` was changed to `Union[str, Callable[[Any, Any], str]]`. Currently, if someone wanted to use `datetime.date` object as a version, they will not be able to correctly format it.

It should be easy to do. Just convert the format into a function if it's a string, and use it as a function everywhere.

```python
if isinstance(prefix_format, str):
    prefix_format = lambda major, minor, str_format=prefix_format: str_format.format(major=major, minor=minor)

...

prefix = prefix_format(major, minor)
```

**Comment by alexschimpf** [comment]
@kunesj @ndejong I'll get back to this PR in some time. Been a lil bit busy lately.

**Comment by alexschimpf** [comment]
I'm closing this PR in favor of this one: https://github.com/alexschimpf/fastapi-versionizer/pull/18

**Pull request closed without merging**
